apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp1
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp1
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.1
  replicas: 3
  selector:
    matchLabels:
      app: myapp1